export function PassengerEnding(userPassengerAmount, setUserPassengerAmountText){
    switch (userPassengerAmount){
        case 1:
            return setUserPassengerAmountText("пассажир");
        case 2:
            return setUserPassengerAmountText("пассажира");
        case 3:
            return setUserPassengerAmountText("пассажира");
        case 4:
            return setUserPassengerAmountText("пассажира");
        case 5:
            return setUserPassengerAmountText("пассажиров");
        case 6:
            return setUserPassengerAmountText("пассажиров");
        case 7:
            return setUserPassengerAmountText("пассажиров");
        case 8:
            return setUserPassengerAmountText("пассажиров");
        case 9:
            return setUserPassengerAmountText("пассажиров");
        case 10:
            return setUserPassengerAmountText("пассажиров");
        case 11:
            return setUserPassengerAmountText("пассажиров");
        case 12:
            return setUserPassengerAmountText("пассажиров");
        case 13:
            return setUserPassengerAmountText("пассажиров");
        case 14:
            return setUserPassengerAmountText("пассажиров");
        case 15:
            return setUserPassengerAmountText("пассажиров");
        case 16:
            return setUserPassengerAmountText("пассажиров");
        case 17:
            return setUserPassengerAmountText("пассажиров");
        case 18:
            return setUserPassengerAmountText("пассажиров");
        case 19:
            return setUserPassengerAmountText("пассажиров");
        case 20:
            return setUserPassengerAmountText("пассажиров");
        case 21:
            return setUserPassengerAmountText("пассажир");
        case 22:
            return setUserPassengerAmountText("пассажира");
        case 23:
            return setUserPassengerAmountText("пассажира");
        case 24:
            return setUserPassengerAmountText("пассажира");
        case 25:
            return setUserPassengerAmountText("пассажиров");
        case 26:
            return setUserPassengerAmountText("пассажиров");
        case 27:
            return setUserPassengerAmountText("пассажиров");
        default:
            return "Ошибка";
    }
}